### ISSUE TITLE
Fix map

### ISSUE THREAD

**Issue by Trimatix** [Trimatix/GOF2BountyBot#64]
Wah'norr should jump to Ni'mrrod and K'ontrr.
check all other systems.
give new screenshot in $map

**Comment by silverben10** [comment]
Here's an updated map image with the new routes added. I'm not entirely sure where to find the information about which systems can jump to where, but if you lmk I can update the map fully 👍 

[Link to updated map](https://i.imgur.com/TmPgPd3.png)
